#!/bin/sh

#
# /etc/init.d/S60i2c2oled
#
# 2021-04-19 by venice
# License GPL v3
# Release based on S60tty2oled
#

SCRIPT="i2c2oled"
DAEMONSCRIPT="/usr/bin/${SCRIPT}"

# Start
start() {
    if [[ -x ${DAEMONSCRIPT} ]]; then
      echo "Starting i2c2oled..."
      ${DAEMONSCRIPT} &
    else
      echo "${DAEMONSCRIPT} not found!"
    fi
}

# Stop
stop() {
    echo "Stopping i2c2oled..."
    killall ${SCRIPT}
    #killall ${DAEMONSCRIPT}
}

case "$1" in
  start)
        start
        ;;
  stop) 
        stop
        ;;
  restart)
        stop
        start
        ;;
#  reload)
#       reload
#       ;;
  *)
#        echo "Usage: $0 {start|stop|restart|reload}"
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
